### ISSUE TITLE
Failed connections reject with (undefined) data instead of error

### ISSUE THREAD

**Issue by bmomberger-bitovi** [bitovi/testee-client#38]
Re: https://github.com/bitovi/testee-client/blob/master/src/runner.js#L23

This has been leading to many unhandled promise rejections with `undefined` instead of anything helpful, and it was hard to track down.  Shouldn't this reject with `error` when there is an error?

**Comment by andrejewski** [comment]
This has been resolved in a more recent rewrite, see https://github.com/bitovi/testee-client/blob/01cf177b4bbf99b87e2fe1a5fecd9300a3053949/src/runner.js#L19.
